### ISSUE TITLE
We need a way to add line breaks to event information

### ISSUE THREAD

**Issue by leomelin** [webDevAndSausages/webdevandsausages.v2#10]
Mostly the "what" part in event information needs possibility to add line breaks to allow listing some time table info, more info about presentations etc.

**Comment by RikuVan** [comment]
One easy solution would be to use markdown. It should be trivial to make this change. Will have a look soon.

**Comment by RikuVan** [comment]
I add `<Markup />` components for the front page, including the what, who, and where fields. using https://github.com/developit/preact-markup. Used this because it is lightweight but something like React-markdown would also work if needed. So now you can add a </br> inside a string in the db.
