### ISSUE TITLE
doesn't work on iPhone chrome

### ISSUE THREAD

**Issue by RikuVan** [webDevAndSausages/webdevandsausages.v2#5]

**Comment by leomelin** [comment]
shiit, safari neither

**Comment by leomelin** [comment]
![screen shot 2018-02-20 at 9 08 01](https://user-images.githubusercontent.com/2268969/36411339-c9b3ffe2-161d-11e8-9509-3685c2f5d43c.png)

**Comment by RikuVan** [comment]
added the missing polyfill
