### ISSUE TITLE
Registration/Cancellation/Verification tabs problem on narrow screen

### ISSUE THREAD

**Issue by leomelin** [webDevAndSausages/webdevandsausages.v2#9]
Registration/Cancellation/Verification tabs on narrow screen are stacked on top of each other and it's unclear which one is selected

![screen shot 2018-05-17 at 8 19 25](https://user-images.githubusercontent.com/2268969/40158063-210ee736-59ab-11e8-8050-2631b98d075a.png)

Also the tab "Verification" should probably be labeled "Check registration" because that's the link in the email also

**Comment by RikuVan** [comment]
Changed to make background orange on phone

<img width="412" alt="screen shot 2018-08-03 at 18 39 26" src="https://user-images.githubusercontent.com/7317771/43652291-7679d58e-974d-11e8-8f19-83680c70022c.png">
